# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - npm install
    
stages:
    - test
    - deploy

lint:
    stage: test
    script:
        - npm run lint

deployAWS:
    only:
        - master
    stage: deploy
    script:
        - bash deploy.sh